model_name: "red"
learning_rate: 0.001
batch_size: 32
num_epochs: 10
train_data_path: "../data/KALI_LINUX_TOOLS_DATASET.jsonl"
validation_data_path: "../data/KALI_LINUX_TOOLS_DATASET.jsonl"
output_dir: "../output"
logging_steps: 50
save_steps: 100
evaluation_strategy: "steps"
max_seq_length: 128
seed: 42